apiVersion: v1
kind: Pod
metadata:
  name: airflow-base
spec:
  containers:
    - name: base
      image: <your image>
      imagePullPolicy: Always
      env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: KubernetesExecutor
        - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
          value: "false"
      volumeMounts:
        - name: logs
          mountPath: /opt/airflow/logs
  restartPolicy: Never
  imagePullSecrets:
    - name: <your PullSecrets>
  volumes:
    - name: logs
      emptyDir: {}
