airflow:
  image:
    repository: harbor.gistda.or.th/registry/datapipeline/main
    tag: 63ac2dfc
    pullPolicy: Always
  imagePullSecrets:
    - name: gistda-habor
    
  config:
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: "rbYLD513AanqmnBSKkRgxhFbqabTQ2IBMSLagucnNlQ="
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
    AIRFLOW__CORE__LOAD_EXAMPLES: "true"
    AIRFLOW__API__AUTH_BACKEND: airflow.api.auth.backend.basic_auth
    AIRFLOW__FLASK_LIMITER__STORAGE_URI: "redis://redis-master:6379"
    AIRFLOW__WEBSERVER__BASE_URL: http://172.27.153.10:30080  # หรือ URL/IP ที่เข้าถึงได้
    AIRFLOW__KUBERNETES__WORKER_LOG_SERVER_PORT: 8080
    AIRFLOW__KUBERNETES__WORKER_LOG_SERVER_HOST: airflow-worker.airflow.svc.cluster.local
    AIRFLOW__WEBSERVER__WEB_SERVER_HOST: webserver
    AIRFLOW__WEBSERVER__WEB_SERVER_PORT: 8080
    AIRFLOW__LOGGING__REMOTE_LOGGING: "True"
    AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER: "s3://gi-disaster/airflow-logs"
    AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID: "minio_s3_conn"
    AIRFLOW__LOGGING__LOGGING_LEVEL: "INFO"
    AIRFLOW__LOGGING__HOSTNAME_CALLABLE: "socket.getfqdn"
    AIRFLOW__KUBERNETES__POD_TEMPLATE_FILE: /opt/airflow/pod_templates/pod_template_file.yaml

  users:
    - username: airflow
      password: airflow
      role: Admin
      email: airflow@example.com
      firstName: Air
      lastName: Flow

webserverSecretKey: 8ec500580b49eb5188bedb07c4d10642

dags:
  gitSync:
    enabled: true
    repo: "https://gitlab.gistda.or.th/tawatchai/datapipeline.git"
    branch: main
    subPath: dags

logs:
  persistence:
    enabled: false

postgresql:
  enabled: true
  auth:
    username: airflow
    password: airflow
    database: airflow

redis:
  enabled: true

webserver:
  enabled: true
  service:
    type: NodePort
    ports:
      - name: pipeline-pod
        port: 8080
        targetPort: 8080
        nodePort: 30081

  livenessProbe:
    initialDelaySeconds: 90  # เพิ่มจาก 60
    timeoutSeconds: 10
    periodSeconds: 10
    failureThreshold: 10

  readinessProbe:
    initialDelaySeconds: 90
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 10

  startupProbe:
    timeoutSeconds: 30
    periodSeconds: 10
    failureThreshold: 30
    initialDelaySeconds: 20

  resources:
    limits:
      memory: "1Gi"
      cpu: "1"
    requests:
      memory: "250Mi"
      cpu: "100m"

scheduler:
  enabled: true